apiVersion: v1
kind: Service
metadata:
  name: organic-ghee-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: organic-ghee
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: ClusterIP