apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-user: {{ .Values.mongodb.username | b64enc }}
  mongo-password: {{ .Values.mongodb.password | b64enc }}

